source 'https://rubygems.org'
gem 'rails', require: true
gem 'foundation-rails', require: true
gem 'nd_foundation', path: '../..'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
